language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "6.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i
  - npm run lint
  - npm start &
  - npm run webdriver:update
  - npm run webdriver:start &

script:
  - npm test
  - npm run test:e2e
  - npm run build
